print ('++++++++++++++++++++++++++++++++++++++++++++++++++++++')
print('This will be my first Python code')
print('monkeys like to eat bananas')
print(5*2)
print('This is the end of the script, thanks for leaning python with us')
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++++')